# Configuration
baseURL: "https://esdocu.net/"
languageCode: es
title: "Esdocu.net"

enableRobotsTXT: true
enableGitInfo: true
# enableEmoji: false
hasCJKLanguage: true

outputs:
  home: [HTML]
  page: [HTML]
  section: [HTML]

disableKinds:
  - taxonomy

disableHugoGeneratorInject: true

defaultContentLanguage: es
# languages:
#   en:
#     languageName: English
#     weight: 1
#     title: Hextra
#   zh-cn:
#     languageName: 简体中文
#     languageCode: zh-CN
#     weight: 2
#     title: Hextra

# module:
#   hugoVersion:
#     extended: true
#     min: "0.112.0"

#   workspace: hugo.work
#   imports:
#     path: github.com/imfing/hextra

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

enableInlineShortcodes: true

build:
  buildStats:
    disableClasses: false
    disableIDs: false
    disableTags: false
    enable: true

menu:
  main:
    - identifier: inicio
      name: Inicio
      pageRef: /
      weight: 1
    - identifier: manuales
      name: Manuales de programación
      pageRef: /#manuales
      weight: 2
    - identifier: cursos
      name: Nuestros cursos ↗
      url: https://esdocu.dev
      weight: 3
    # - identifier: typescript
    #   name: TypeScript
    #   pageRef: /typescript/comenzando/typescript-desde-cero/
    #   weight: 2
    # - identifier: bootstrap
    #   name: Bootstrap
    #   pageRef: /bootstrap/5.3/getting-started/introduction/
    #   weight: 3
    # - identifier: momentjs
    #   name: Moment.js
    #   pageRef: /momentjs/use-it/
    #   weight: 4
    - identifier: contact
      name: Contacto
      url: mailto:hola.esdocu@gmail.com
      weight: 5
    - name: Search
      weight: 6
      params:
        type: search
    - name: GitHub
      weight: 7
      url: "https://github.com/fabiankaraben/esdocu-net"
      params:
        icon: github

  # sidebar:
  #   - identifier: more
  #     name: More
  #     params:
  #       type: separator
  #     weight: 1
  #   - identifier: about
  #     name: "About"
  #     pageRef: "/about"
  #     weight: 2
  #   - identifier: hugoDocs
  #     name: "Hugo Docs ↗"
  #     url: "https://gohugo.io/documentation/"
  #     weight: 3

params:
  description: Manuales sobre Desarrollo de Software en español. Esdocu.net es la plataforma donde encontrarás manuales open source.

  navbar:
    displayTitle: false
    displayLogo: true
    logo:
      path: assets/site/logo.svg
      dark: assets/site/logo-dark.svg
      width: 103
      height: 20
      # link: /
    width: wide

  page:
    # full (100%), wide (90rem), normal (1280px)
    width: wide

  theme:
    # light | dark | system
    default: system
    displayToggle: true

  footer:
    enable: true
    displayCopyright: true
    displayPoweredBy: false
    width: normal

  displayUpdatedDate: true
  dateFormat: "January 2, 2006"

  # Search
  # flexsearch is enabled by default
  search:
    enable: true
    type: flexsearch

    flexsearch:
      # index page by: content | summary | heading | title
      index: content

  editURL:
    enable: true
    base: "https://github.com/fabiankaraben/esdocu-net/content"

  blog:
    list:
      displayTags: true

  comments:
    enable: false
    type: giscus

    # https://giscus.app/
    giscus:
      repo: imfing/hextra
      repoId: R_kgDOJ9fJag
      category: General
      categoryId: DIC_kwDOJ9fJas4CY7gW
      # mapping: pathname
      # strict: 0
      # reactionsEnabled: 1
      # emitMetadata: 0
      # inputPosition: top
      # lang: en
