services:
  googleAnalytics:
    ID: G-P9N8MVS57V
params:
  # Hostinger banners.
  showHostingerTopBanner: false # Donate
  showHostingerMiddleBanner1: true # Donate
  showHostingerMiddleBanner2: false # Donate
  showHostingerMiddleBanner3: false # Donate
  showHostingerMiddleBanner4: false # Donate
  showHostingerMiddleBanner5: false # Donate
  showHostingerMiddleBanner6: false # Donate
  showHostingerMiddleBanner7: false # Donate
  showHostingerMiddleBanner8: false # Donate
  showHostingerMiddleBanner9: false # Donate
  showHostingerBottomBanner: false # Donate

  # TheMoneytizer Ads.
  # All formats: https://us.themoneytizer.com/ad-units
  showTMConsentBanner: false # CMP (head)
  showTMInText: false # head
  showTMInterstitial: false # head
  showTMPopUnder: false # head :: Intrusive. This format redirects the user directly to an advertiser's page.
  showTMFooterSlideIn: false # footer
  showTMTopBanner: false # content (body) :: BILLBOARD
  showTMMiddleBanner1: false # content (body) :: MEGABANNER
  showTMMiddleBanner2: false # content (body) :: ROBAPÁGINAS
  showTMMiddleBanner3: false # content (body) :: ROBAPÁGINAS INFERIOR
  showTMMiddleBanner4: false # content (body) :: CONTENIDO RECOMENDADO
  showTMMiddleBanner5: false # content (body) :: SPLITSCREEN
  showTMMiddleBanner6: false # content (body) :: -
  showTMMiddleBanner7: false # content (body) :: -
  showTMMiddleBanner8: false # content (body) :: -
  showTMMiddleBanner9: false # content (body) :: -
  showTMBottomBanner: false # content (body) :: MEGABANNER INFERIOR

  # AdCash Ads.
  loadAdCashGlobalScript: false # head
  showAdCashAutotag: false # head
  showAdCashTopBanner: false # content (body) :: -
  showAdCashMiddleBanner1: false # content (body) :: -
  showAdCashMiddleBanner2: false # content (body) :: -
  showAdCashMiddleBanner3: false # content (body) :: -
  showAdCashMiddleBanner4: false # content (body) :: -
  showAdCashMiddleBanner5: false # content (body) :: -
  showAdCashMiddleBanner6: false # content (body) :: -
  showAdCashMiddleBanner7: false # content (body) :: -
  showAdCashMiddleBanner8: false # content (body) :: -
  showAdCashMiddleBanner9: false # content (body) :: -
  showAdCashBottomBanner: false # content (body) :: -

  # Adsterra Ads.
  showAdsterraPopunder: false # end head
  showAdsterraSocialBar: false # end body
  showAdsterraTopBanner: false # content (body) :: -
  showAdsterraMiddleBanner1: false # content (body) :: -
  showAdsterraMiddleBanner2: false # content (body) :: -
  showAdsterraMiddleBanner3: false # content (body) :: -
  showAdsterraMiddleBanner4: false # content (body) :: -
  showAdsterraMiddleBanner5: false # content (body) :: -
  showAdsterraMiddleBanner6: false # content (body) :: -
  showAdsterraMiddleBanner7: false # content (body) :: -
  showAdsterraMiddleBanner8: false # content (body) :: -
  showAdsterraMiddleBanner9: false # content (body) :: -
  showAdsterraBottomBanner: false # content (body) :: -

  # Custom banners.
  showCustomTopBanner: false # Donate
  showCustomMiddleBanner1: false # Donate
  showCustomMiddleBanner2: false # Donate
  showCustomMiddleBanner3: false # Donate
  showCustomMiddleBanner4: false # Donate
  showCustomMiddleBanner5: false # Donate
  showCustomMiddleBanner6: false # Donate
  showCustomMiddleBanner7: false # Donate
  showCustomMiddleBanner8: false # Donate
  showCustomMiddleBanner9: false # Donate
  showCustomBottomBanner: false # Donate

  # Adsense.
  includeAdsenseScript: false