services:
  googleAnalytics:
    ID: G-P9N8MVS57V
params:
  # TheMoneytizer Ads.
  # All formats: https://us.themoneytizer.com/ad-units
  showTMConsentBanner: false # CMP (head)
  showTMInText: false # head
  showTMInterstitial: false # head
  showTMPopUnder: false # head :: Intrusive. This format redirects the user directly to an advertiser's page.
  showTMFooterSlideIn: false # footer
  showTMTopBanner: false # content (body) :: BILLBOARD
  showTMMiddleBanner1: false # content (body) :: MEGABANNER
  showTMMiddleBanner2: false # content (body) :: ROBAPÁGINAS
  showTMMiddleBanner3: false # content (body) :: ROBAPÁGINAS INFERIOR
  showTMMiddleBanner4: false # content (body) :: CONTENIDO RECOMENDADO
  showTMMiddleBanner5: false # content (body) :: SPLITSCREEN
  showTMMiddleBanner6: false # content (body) :: -
  showTMMiddleBanner7: false # content (body) :: -
  showTMMiddleBanner8: false # content (body) :: -
  showTMMiddleBanner9: false # content (body) :: -
  showTMBottomBanner: false # content (body) :: MEGABANNER INFERIOR

  # AdCash Ads.
  loadAdCashGlobalScript: true # head
  showAdCashAutotag: true # head
  showAdCashTopBanner: true # content (body) :: -
  showAdCashMiddleBanner1: true # content (body) :: -
  showAdCashMiddleBanner2: true # content (body) :: -
  showAdCashMiddleBanner3: true # content (body) :: -
  showAdCashMiddleBanner4: true # content (body) :: -
  showAdCashMiddleBanner5: true # content (body) :: -
  showAdCashMiddleBanner6: true # content (body) :: -
  showAdCashMiddleBanner7: true # content (body) :: -
  showAdCashMiddleBanner8: true # content (body) :: -
  showAdCashMiddleBanner9: true # content (body) :: -
  showAdCashBottomBanner: true # content (body) :: -

  # Custom banners.
  showCustomTopBanner: false # Donate
  showCustomMiddleBanner1: false # Donate
  showCustomMiddleBanner2: false # Donate
  showCustomMiddleBanner3: false # Donate
  showCustomMiddleBanner4: false # Donate
  showCustomMiddleBanner5: false # Donate
  showCustomMiddleBanner6: false # Donate
  showCustomMiddleBanner7: false # Donate
  showCustomMiddleBanner8: false # Donate
  showCustomMiddleBanner9: false # Donate
  showCustomBottomBanner: false # Donate

  # Adsense.
  includeAdsenseScript: false