services:
  googleAnalytics:
    ID: G-P9N8MVS57V
params:
  # TheMoneytizer Ads.
  # All formats: https://us.themoneytizer.com/ad-units
  showTMConsentBanner: true # CMP (head)
  showTMInText: true # head
  showTMInterstitial: true # head
  showTMPopUnder: false # head :: Intrusive. This format redirects the user directly to an advertiser's page.
  showTMFooterSlideIn: true # footer
  showTMTopBanner: true # content (body) :: BILLBOARD
  showTMMiddleBanner1: true # content (body) :: MEGABANNER
  showTMMiddleBanner2: true # content (body) :: ROBAPÁGINAS
  showTMMiddleBanner3: true # content (body) :: ROBAPÁGINAS INFERIOR
  showTMMiddleBanner4: true # content (body) :: CONTENIDO RECOMENDADO
  showTMMiddleBanner5: true # content (body) :: SPLITSCREEN
  showTMMiddleBanner6: true # content (body) :: -
  showTMMiddleBanner7: true # content (body) :: -
  showTMMiddleBanner8: true # content (body) :: -
  showTMMiddleBanner9: true # content (body) :: -
  showTMBottomBanner: true # content (body) :: MEGABANNER INFERIOR

  # Custom banners.
  showCustomTopBanner: false # Donate
  showCustomMiddleBanner1: false # Donate
  showCustomMiddleBanner2: false # Donate
  showCustomMiddleBanner3: false # Donate
  showCustomMiddleBanner4: false # Donate
  showCustomMiddleBanner5: false # Donate
  showCustomMiddleBanner6: false # Donate
  showCustomMiddleBanner7: false # Donate
  showCustomMiddleBanner8: false # Donate
  showCustomMiddleBanner9: false # Donate
  showCustomBottomBanner: false # Donate

  # Adsense.
  includeAdsenseScript: false