services:
  googleAnalytics:
    ID: G-P9N8MVS57V
params:
  # TheMoneytizer Ads.
  # All formats: https://us.themoneytizer.com/ad-units
  showTMConsentBanner: true # CMP (head)
  showTMInText: false # head
  showTMInterstitial: false # head
  showTMPopUnder: false # head :: Intrusive. This format redirects the user directly to an advertiser's page.
  showTMFooterSlideIn: false # footer
  showTMTopBanner: false # content (body) :: BILLBOARD
  showTMMiddleBanner1: false # content (body) :: MEGABANNER
  showTMMiddleBanner2: false # content (body) :: ROBAPÁGINAS
  showTMMiddleBanner3: false # content (body) :: ROBAPÁGINAS INFERIOR
  showTMMiddleBanner4: false # content (body) :: CONTENIDO RECOMENDADO
  showTMMiddleBanner5: false # content (body) :: SPLITSCREEN
  showTMMiddleBanner6: false # content (body) :: -
  showTMMiddleBanner7: false # content (body) :: -
  showTMMiddleBanner8: false # content (body) :: -
  showTMMiddleBanner9: false # content (body) :: -
  showTMBottomBanner: false # content (body) :: MEGABANNER INFERIOR

  # Custom banners.
  showCustomTopBanner: true # Donate
  showCustomMiddleBanner1: true # Donate
  showCustomMiddleBanner2: true # Donate
  showCustomMiddleBanner3: true # Donate
  showCustomMiddleBanner4: true # Donate
  showCustomMiddleBanner5: true # Donate
  showCustomMiddleBanner6: true # Donate
  showCustomMiddleBanner7: true # Donate
  showCustomMiddleBanner8: true # Donate
  showCustomMiddleBanner9: true # Donate
  showCustomBottomBanner: true # Donate

  # Adsense.
  includeAdsenseScript: false